### PR TITLE
Console commands

### PR DESCRIPTION
**Pull request by magnusnordlander**
I've added console commands to send messages from a CLI. Basically, the first argument is the FQCN of the message, and the following arguments are constructor args. I thought this might be useful in other projects as well.

### CODE REVIEW

**Comment by cmodijk** [comment]
@magnusnordlander Tnx for taking the time to make this pull request. But could you explain in what situation you want to use this instead of creating specific CLI commands for the project you are using?

**Comment by magnusnordlander** [comment]
There's really no situation in which I would prefer to use this CLI command instead of a specific CLI command, if it makes sense to create a specific CLI command, that would likely always be preferable.

However, not all messages are such that it makes sense to create a specific CLI command for them. If you're e.g. debugging a message handler, or manually fixing the effects of a bug or something similar, it sometimes makes sense to be able to send commands to the command bus, or to dispatch events. Now, granted, you could use something like psysh instead, but sometimes it just makes more sense to have a simple command like this.

**Comment by cmodijk** [comment]
To be honest i'm not a fan of this implementation it has several drawbacks of implementing this in the core of `SimpleBus/SymfonyBridge`. I truly believe that if you want to send a command to a handler you should always send a valid command. This cli command allows me to bypass al the rules that are defined before the construction that normally happens from within a project. I understand that this is a way to debug a command handler but i believe this is the task for a unit test to test your handler and the command. 

The second problem I can see with this is type hinting some commands could be type hinted to accept a `int` or even a value holder in our case that is sometimes true and this does not allow me to define that types of cases.

**Comment by matthiasnoback** [comment]
Hi @magnusnordlander, just wanted to say: thanks for considering this PR. It seems like a useful thing to have, but I agree with @cmodijk (who is the new maintainer of the SimpleBus libraries) that this shouldn't be part of the library. SimpleBus doesn't make assumptions about how the command gets created (for example, while you assume constructor arguments here, I often just use public properties). Hence, I don't feel that this console command would lead to confusion.

**Comment by magnusnordlander** [comment]
No hard feelings, I'll simply stash this away in a bundle of my own instead :)

**Comment by matthiasnoback** [comment]
👍

**Pull request closed without merging**
