### PR TITLE
Corrects the attribute name in command handler service definitions

### PR DESCRIPTION
**Pull request by tonydub**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Sorry, this is no fix ;) "handles" is used for command handlers, "subscribes_to" is used for event subscribers.

**Comment by tonydub** [comment]
Hello,

Sorry, I read too fast :-)

2015-02-18 8:28 GMT+01:00 Matthias Noback notifications@github.com:

**Comment by matthiasnoback** [comment]
Thanks anyway!

**Comment by hacfi** [comment]
This is very confusing! On
http://simplebus.github.io/SymfonyBridge/doc/command_bus_bundle.html is says `..change the value of the subscribes_to attribute..` and `Make sure that the value of subscribes_to matches...` but the code example inbetween uses `{ name: command_handler, handles: register_user }`. it should be handles!?

**Comment by matthiasnoback** [comment]
@hacfi You're right, hence all the confusion in this and other PRs :) I'll fix it.

**Comment by matthiasnoback** [comment]
@hacfi Fixed!

**Comment by hacfi** [comment]
Lovely..thanks! This project is great fun..hope to use it on my job soon!!

**Comment by matthiasnoback** [comment]
Thanks! And that's really great to hear. Let me know if it has proven to be useful in some project.

**Pull request closed without merging**
