### PR TITLE
composer: allow installing Symfony 3 components

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for reporting! According to https://getcomposer.org/doc/articles/versions.md it should be a double pipe though (`||`).

**Comment by xabbuh** [comment]
Composer actually supports both ways: https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionParser.php#L250

**Comment by matthiasnoback** [comment]
Nice, thanks! I'll merge it then :)

**Comment by TomasVotruba** [comment]
@matthiasnoback Thanks!

**Pull request merged**
