### PR TITLE
Fix section typo

### PR DESCRIPTION
**Pull request by ifdattic**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for reporting, but I actually meant this to be inside a block (an "aside"), since it's not part of the main text :)

**Comment by ifdattic** [comment]
Oh, if you meant it as an aside it makes sense then :)

To mean this just looked like it could be fine as a normal section (were is a logging in middlewares which looks fine as "aside").

**Comment by matthiasnoback** [comment]
Right, no problem. I guess maybe it is a bit strange, having two asides one
after another ;)
Op 15 jun. 2015 16:00 schreef "Andrew Marcinkevičius" <
notifications@github.com>:

**Comment by ifdattic** [comment]
It depends. Like on the http://simplebus.github.io/MessageBus/doc/command_bus.html page the logging in aside makes sense as before is being talked about middleware & this logging is talking about middleware.

On this page the logging doesn't mention anything about middlewares so it feels more like a separate section.

**Comment by matthiasnoback** [comment]
So, you convinced me, there you go! Thanks :)

**Comment by ifdattic** [comment]
Glad to help :)

**Pull request merged**
