### PR TITLE
Add class based aliases for CommandBus and EventBus

### PR DESCRIPTION
**Pull request by ruudk**
See https://github.com/SimpleBus/docs/pull/44

@kbond Can you test this?

### CODE REVIEW

**Comment by kbond** [comment]
This works!

**Comment by cmodijk** [comment]
Merged thanks @ruudk!

**Comment by ruudk** [comment]
@kbond Tagged https://github.com/SimpleBus/SymfonyBridge/releases/tag/v5.1.1

**Comment by kbond** [comment]
Perfect, thanks @ruudk!

**Pull request merged**
