### PR TITLE
Fix typo handles_recorded_mesages_middleware

### PR DESCRIPTION
**Pull request by krizon**
Changes the service id `simple_bus.event_bus.handles_recorded_mesages_middleware` in `simple_bus.event_bus.handles_recorded_messages_middleware`

### CODE REVIEW

**Comment by xabbuh** [comment]
Maybe it would be a good idea to add an alias for the old service id in case someone relied on the existing one.

**Comment by cmodijk** [comment]
Or just create a major release and mark it in a upgrade guide. Besides the service is already marked as private so people should not use it in the first place.

**Comment by matthiasnoback** [comment]
Even though the service shouldn't be used directly by people, I think we should not rename a service. As @xabbuh suggested, we should simply add an alias (or better: rename this service, and add an alias which is the old name including the typo). If you change this @krizon, I'll merge it of course :)

**Comment by matthiasnoback** [comment]
Finally merged and tagged a new patch release. Thanks!

**Pull request closed without merging**
