### PR TITLE
Add `CommandBus` and `EventBus` classes to support Symfony Autowiring

### PR DESCRIPTION
**Pull request by ruudk**
See https://github.com/SimpleBus/MessageBus/issues/73

### CODE REVIEW

**Comment by ruudk** [comment]
@cmodijk WDYT?

**Comment by cmodijk** [comment]
@ruudk Thanks!

**Comment by cmodijk** [comment]
@ruudk We should also write some docs about this new feature can you create that? 
* https://github.com/SimpleBus/docs

**Comment by ruudk** [comment]
@cmodijk I was thinking about creating a new release (after #53 is merged). But when I looked at the diff I was wondering if this PR was some kind of BC break? Since it changes the class of the service. The implementation extends from the original class, so I guess we are fine, right?

**Comment by cmodijk** [comment]
I think we are fine here.

**Pull request merged**
