### PR TITLE
Do not stumble on leading backslash when using class names to identify messages

### PR DESCRIPTION
**Pull request by dbu**
fix #22

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks! Could you make the same change in `RegisterHandlers` as well?

**Comment by dbu** [comment]
ok, willdo.

do you see how i broke the smoketest?

**Comment by dbu** [comment]
changed RegisterHandlers too. the smoke test also fails on master when i execute it locally. can you restart the travis build for the master branch to see if there is some version mismatch going on?

**Comment by matthiasnoback** [comment]
When I checkout master it just works. However, the error occurs because the order of the arguments for `ltrim` is not right - it should be `ltrim($key, '\\')` ;)

**Comment by dbu** [comment]
now i feel a bit stupid. changed the order. tests work for me locally, lets see if travis agrees.

**Comment by matthiasnoback** [comment]
No problem! Thanks @dbu.

**Pull request merged**
